apiVersion: ubichill.youkan.uk/v1alpha1
kind: AvatarIndex
metadata:
  name: avatar-templates
  version: "1.0.0"
templates:
  - templates/character_oji_03_blue_brown.yaml
  - templates/character_tenshi_gold.yaml
  - templates/cat_halloween_purple.yaml
  - templates/custom-single.yaml
