/**
 * build-workers.mjs
 *
 * plugins/ 以下の plugin.json を自動探索し、entry.worker が存在する
 * プラグインの Worker コードを esbuild でバンドルします。
 *
 * 出力物:
 *   1. <frontend>/src/<Name>Behaviour.gen.ts  — 後方互換（static import 用）
 *   2. dist/workers/<pluginId>@<version>.js   — CDN 配布用（URL ベースロード用）
 *
 * URL ベースの動的ロードに移行する場合は dist/workers/ を CDN にアップロードし、
 * usePluginWorker({ pluginCodeUrl: 'https://cdn.example.com/...' }) で参照する。
 */

import * as esbuild from 'esbuild';
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { basename, dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

// --dist-dir=<path> で出力先を上書き可能（デフォルト: dist/workers/）
const distDirArg = process.argv.slice(2).find((a) => a.startsWith('--dist-dir='));
const distDir = distDirArg ? join(root, distDirArg.split('=')[1]) : join(root, 'dist', 'workers');

// ============================================================
// plugin.json の自動探索
// ============================================================

function findPluginJsonFiles(pluginsDir) {
    const results = [];
    for (const pluginName of readdirSync(pluginsDir, { withFileTypes: true })) {
        if (!pluginName.isDirectory()) continue;
        const pluginJsonPath = join(pluginsDir, pluginName.name, 'plugin.json');
        if (existsSync(pluginJsonPath)) {
            results.push(pluginJsonPath);
        }
    }
    return results;
}

// ============================================================
// ビルド
// ============================================================

export async function buildWorker(pluginJsonPath) {
    const pluginDir = dirname(pluginJsonPath);
    const pluginJson = JSON.parse(readFileSync(pluginJsonPath, 'utf-8'));

    const workerEntry = pluginJson.entry?.worker;
    if (!workerEntry) return; // worker なしプラグインはスキップ

    const pluginId = pluginJson.id;         // 例: "pen:pen"
    const pluginName = pluginJson.name;     // 例: "Pen"
    const version = pluginJson.version;    // 例: "2.0.0"
    const safeId = pluginId.replace(/[^a-zA-Z0-9]/g, '_'); // ファイル名に使える形式

    const entryPath = join(pluginDir, workerEntry);
    if (!existsSync(entryPath)) {
        console.error(`❌ [${pluginId}] entry.worker が見つかりません: ${entryPath}`);
        return;
    }

    // worker/tsconfig.json を探す（なければルートの tsconfig を使用）
    const workerTsconfig = join(pluginDir, 'worker', 'tsconfig.json');
    const tsconfig = existsSync(workerTsconfig) ? workerTsconfig : undefined;

    const result = await esbuild.build({
        entryPoints: [entryPath],
        bundle: true,
        format: 'iife',
        platform: 'browser',
        target: 'es2020',
        // @ubichill/sdk は型と EcsEventType 等の値をエクスポートするためバンドルに含める。
        // UbiSDK インスタンスは `Ubi` グローバルとして実行時に注入されるが、
        // EcsEventType などの定数は bundleで静的に解決する必要がある。
        write: false,
        minify: false,
        tsconfig,
    });

    const code = result.outputFiles[0].text;

    // --- 出力 1: CDN 配布用 JS ---
    mkdirSync(distDir, { recursive: true });
    const distFile = join(distDir, `${safeId}@${version}.js`);
    writeFileSync(distFile, code, 'utf-8');

    // --- 出力 2: .gen.ts (後方互換・static import 用) ---
    // frontend/src/ が存在する場合のみ生成
    const frontendSrc = join(pluginDir, 'frontend', 'src');
    if (existsSync(frontendSrc)) {
        const exportName = `${pluginName.toLowerCase().replace(/[^a-zA-Z0-9]/g, '')}PluginCode`;
        const genFile = join(frontendSrc, `${pluginName}Behaviour.gen.ts`);
        const relEntry = relative(root, entryPath).replace(/\\/g, '/');

        const generated = [
            `// AUTO-GENERATED by scripts/build-workers.mjs — DO NOT EDIT`,
            `// Source: ${relEntry}`,
            `// Run \`pnpm build:workers\` to regenerate`,
            ``,
            `export const ${exportName} = ${JSON.stringify(code)};`,
        ].join('\n');

        writeFileSync(genFile, generated, 'utf-8');
        console.log(`✅ [${pluginId}] .gen.ts → ${relative(root, genFile)}`);
    }

    console.log(`✅ [${pluginId}] dist  → dist/workers/${basename(distFile)}`);
}

// ============================================================
// エントリーポイント
// ============================================================

async function main() {
    console.log('🔨 Building plugin workers...');
    const pluginsDir = join(root, 'plugins');
    const pluginJsonFiles = findPluginJsonFiles(pluginsDir);

    if (pluginJsonFiles.length === 0) {
        console.warn('⚠️  plugin.json が見つかりません');
        return;
    }

    for (const pluginJsonPath of pluginJsonFiles) {
        await buildWorker(pluginJsonPath);
    }

    console.log('🎉 All workers built.');
    console.log(`📦 CDN 配布用: dist/workers/`);
    console.log(`   PluginHostManager.fromUrl('https://cdn.example.com/plugins/<file>.js', { ... })`);
    console.log(`   usePluginWorker({ pluginCodeUrl: 'https://...', ... })`);
}

main().catch((err) => {
    console.error('❌ Worker build failed:', err);
    process.exit(1);
});
