/**
 * build-workers.mjs
 *
 * Plugin worker (TypeScript) を esbuild でバンドルし、
 * フロントエンドが import できる .gen.ts ファイルとして出力します。
 *
 * 将来: Ubicrate CLI がこの処理を担当します。
 */

import * as esbuild from 'esbuild';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const workers = [
    {
        entry: 'plugins/pen/worker/src/index.ts',
        output: 'plugins/pen/frontend/src/PenBehaviour.gen.ts',
        exportName: 'penPluginCode',
        pluginId: 'pen',
    },
];

async function buildWorker({ entry, output, exportName, pluginId }) {
    const result = await esbuild.build({
        entryPoints: [join(root, entry)],
        bundle: true,
        format: 'iife',
        platform: 'browser',
        target: 'es2020',
        // @ubichill/sdk は Worker 内で型のみ使用。実行時は Ubi がサンドボックス内に注入される。
        external: ['@ubichill/sdk'],
        write: false,
        minify: false,
        // tsconfig の paths を解決 (worker/tsconfig.json のパスエイリアス)
        tsconfig: join(root, 'plugins/pen/worker/tsconfig.json'),
    });

    const code = result.outputFiles[0].text;

    const generated = [
        `// AUTO-GENERATED by scripts/build-workers.mjs — DO NOT EDIT`,
        `// Source: ${entry}`,
        `// Run \`pnpm build:workers\` to regenerate`,
        ``,
        `export const ${exportName} = ${JSON.stringify(code)};`,
    ].join('\n');

    writeFileSync(join(root, output), generated, 'utf-8');
    console.log(`✅ [${pluginId}] worker built → ${output}`);
}

async function main() {
    console.log('🔨 Building plugin workers...');
    for (const worker of workers) {
        await buildWorker(worker);
    }
    console.log('🎉 All workers built.');
}

main().catch((err) => {
    console.error('❌ Worker build failed:', err);
    process.exit(1);
});
