kind: World
spec:
  capacity:
    max: 20
    default: 10
  displayName: ちるわ
  description: "公式のチルワールド"
  thumbnail: "https://i0.wp.com/game-pile.com/wp-content/uploads/fbe2e41743a5255912ac5c4a9d944a5f.jpg?ssl=1"
  environment:
    worldSize:
      width: 2000
      height: 1500
    backgroundColor: "#F0F8FF"
  dependencies:
    - name: video-player
      source:
        path: plugins/video-player
        type: repository
    - name: pen
      source:
        path: plugins/pen
        type: repository
    - name: avatar
      source:
        path: plugins/avatar
        type: repository
  initialEntities:
    - id: video-player
      tags: []
      children:
        - id: video-player-screen
          tags: []
          children: []
          transform:
            h: 613
            w: 1060
            x: 25
            y: 21
            z: 2
            scale: 1
            rotation: 0
          components:
            - data:
                loop: none
                apiBase: /plugins/video-player/api
                shuffle: false
                duration: 0
                playlist: []
                isPlaying: false
                currentTime: 0
                currentIndex: 0
              type: video-player:screen
        - id: video-player-controls
          tags: []
          children: []
          transform:
            h: 100
            w: 740
            x: 20
            y: 653
            z: 200
            scale: 1
            rotation: 0
          components:
            - data: {}
              type: video-player:controls
        - id: playlist
          tags: []
          children: []
          transform:
            h: 610
            w: 322
            x: 1095
            y: 37
            z: 1
            scale: 1
            rotation: 0
          components:
            - data:
                playlist:
                  - id: https://www.youtube.com/watch?v=w3vt4U13QYM&t=45s
                    mode: video
                    title: 原神ASMR／睡眠用BGM🎧ナヒーダと雫の音。@ヴァナラーナ｜リラックス・安眠・作業用
              type: video-player:playlist
        - id: search
          tags: []
          children: []
          transform:
            h: 617
            w: 379
            x: 1433
            y: 33
            z: 1
            scale: 1
            rotation: 0
          components:
            - data: {}
              type: video-player:search
      transform:
        h: 781
        w: 1847
        x: 84
        y: 93
        z: 3
        scale: 1
        rotation: 0
      components: []
    - id: pentray
      tags: []
      children:
        - id: pen
          tags: []
          children: []
          transform:
            h: 48
            w: 55
            x: 9
            y: 7
            z: 6
            scale: 1
            rotation: 0
          components:
            - data:
                color: "#93bcf0"
                strokeWidth: 4
              type: pen:pen
        - id: pen2
          tags: []
          children: []
          transform:
            h: 57
            w: 57
            x: 76
            y: 6
            z: 6
            scale: 1
            rotation: 0
          components:
            - data:
                color: "#1a1a1a"
                strokeWidth: 4
              type: pen:pen
      transform:
        h: 67
        w: 266
        x: 609
        y: 17
        z: 4
        scale: 1
        rotation: 0
      components:
        - data: {}
          type: pen:tray
    - id: pen-canvas
      tags: []
      children: []
      transform:
        x: 530
        y: 49
        z: 60
        scale: 1
        rotation: 0
      components:
        - data: {}
          type: pen:canvas
    - id: pentray2
      tags: []
      children:
        - id: pen-copy
          tags: []
          children: []
          transform:
            h: 48
            w: 55
            x: 9
            y: 14
            z: 6
            scale: 1
            rotation: 0
          components:
            - data:
                color: "#93bcf0"
                strokeWidth: 4
              type: pen:pen
        - id: pen-copy-2
          tags: []
          children: []
          transform:
            h: 48
            w: 55
            x: 64
            y: 14
            z: 6
            scale: 1
            rotation: 0
          components:
            - data:
                color: "#44474b"
                strokeWidth: 4
              type: pen:pen
      transform:
        h: 75
        w: 175
        x: 1004
        y: 8
        z: 7
        scale: 1
        rotation: 0
      components:
        - data: {}
          type: pen:tray
metadata:
  name: qddq511a3y2su8bq7gsf2
  author:
    name: devようかん
  version: 1.0.0
apiVersion: ubichill.com/v1alpha1
