apiVersion: ubichill.com/v1alpha1
kind: Room
metadata:
  name: default
  version: "1.0.0"
  author:
    name: "Ubichill Team"
spec:
  displayName: "デフォルトルーム"
  description: "Ubichill のデフォルトコラボレーションスペース"
  
  capacity:
    default: 10
    max: 20
  
  environment:
    backgroundColor: "#F0F8FF"
    worldSize:
      width: 2000
      height: 1500
  
  # パッケージ依存関係
  dependencies:
    - name: pen
      source:
        type: repository
        path: "packages/pen"
  
  # 初期配置エンティティ（ペンを1つ配置）
  initialEntities:
    - kind: "pen:pen"
      transform:
        x: 400
        y: 300
        z: 1
        scale: 1
        rotation: -45
      data:
        color: "#228BE6"
  
  permissions:
    allowGuestCreate: true
    allowGuestDelete: false
