apiVersion: ubichill.com/v1alpha1
kind: Room
metadata:
  name: workspace
  version: "1.0.0"
  author:
    name: "Ubichill Team"
spec:
  displayName: "ワークスペース"
  description: "落ち着いた雰囲気の作業空間"
  thumbnail: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400&h=200&fit=crop&q=80"
  
  capacity:
    default: 8
    max: 15
  
  environment:
    backgroundColor: "#1a1a2e"
    backgroundImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1920&q=80"
    worldSize:
      width: 2000
      height: 1500
  
  dependencies:
    - name: pen
      source:
        type: repository
        path: "packages/pen"
  
  initialEntities:
    - kind: "pen:pen"
      transform:
        x: 600
        y: 400
        z: 1
        scale: 1
        rotation: 0
      data:
        color: "#E6E6E6"
  
  permissions:
    allowGuestCreate: true
    allowGuestDelete: false
