{{- if and .Values.backend.enabled .Values.worlds.registryToken (not .Values.worlds.existingTokenSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ubichill.fullname" . }}-worlds-token
  labels:
    {{- include "ubichill.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.worlds.registryToken | quote }}
{{- end }}
